{% set version = "1.1.1rc2" %}
{% set sha256 = "511027d531edb016131788f9af04ecb26c688a0f65aba0b337238163c252987d" %}
{% set build_num = "0" %}

package:
  name: gpi
  version: {{ version }}

source:
  url: https://github.com/gpilab/framework/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_num }}
  skip_compile_pyc:
    - "include/PyFI/*.py"
  skip: true  # [win]
  skip: true  # [py2k]

requirements:
  host:
    - python {{ python }}
  run:
    - eigen
    - fftw
    - h5py
    - numpy >=1.11,<2
    - pillow
    - psutil
    - pyopengl
    - {{ pin_compatible('python') }}
    - pyqt  # enforces qt at same version
    - qtpy
    - sip
    - qimage2ndarray
#    - xorg-libsm  # [linux]
#    - xorg-libxcb  # [linux]
#    - xorg-libxrender  # [linux]

test:
  imports:
    - gpi
  commands:
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c "gpi --help"  # [linux]
    - gpi --help  # [osx]

about:
  home: http://gpilab.com
  license: GPL3
  license_family: GPL
  license_file: LICENSE
  summary: "GPI - Graphical Programming Interface Development Framework"
  description: |
    GPI can be thought of as an integrated development environment for Python. 
    Algorithm elements (i.e., nodes) can be linked together to form a flow diagram
    that is then executed according to the diagram hierarchy. At the node level,
    the common API and UI elements allow other developers to easily integrate 
    and use your code. The visual and modular nature of GPI also allows concise
    communication of your work with your collaborators and provides an intuitive
    mechanism for others to start interacting with your research.
  doc_url: http://gpilab.com/documentation
  dev_url: https://github.com/gpilab/framework

extra:
  recipe-maintainers:
    - borupdaniel
    - aganders3
